//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosClinicos
    {
        public int IdDatosClinicos { get; set; }
        public int IdPersona { get; set; }
        public Nullable<System.DateTime> FechaInicioSintomas { get; set; }
        public bool Fiebre { get; set; }
        public bool Tos { get; set; }
        public bool DolorToracico { get; set; }
        public bool DificultadRespiratoria { get; set; }
        public bool Cefalea { get; set; }
        public bool Irritabilidad { get; set; }
        public bool Diarrea { get; set; }
        public bool Vomito { get; set; }
        public bool Calosfrios { get; set; }
        public bool DolorAbdominal { get; set; }
        public bool Mialgias { get; set; }
        public bool Artralgias { get; set; }
        public bool AtaqueAlEdoGral { get; set; }
        public bool Rinorrea { get; set; }
        public bool Polipnea { get; set; }
        public bool Odinofagia { get; set; }
        public bool Conjuntivitis { get; set; }
        public bool Cianosis { get; set; }
        public bool Convulsiones { get; set; }
        public string OtroSintoma { get; set; }
        public bool Diabetes { get; set; }
        public bool EPOC { get; set; }
        public bool Asma { get; set; }
        public bool Inmunosupresion { get; set; }
        public bool Hipertension { get; set; }
        public bool VihSida { get; set; }
        public bool EnfermedadCardio { get; set; }
        public bool Obesidad { get; set; }
        public bool InsuficienciaRenalCronica { get; set; }
        public bool InsuficienciaHepaticaCronica { get; set; }
        public bool Tabaquismo { get; set; }
        public string OtroCoMorbilidad { get; set; }
    
        public virtual DatosGenerales DatosGenerales { get; set; }
    }
}
