//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosNotificante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosNotificante()
        {
            this.DatosGenerales = new HashSet<DatosGenerales>();
        }
    
        public int IdUnidadNotificante { get; set; }
        public string Entidad { get; set; }
        public string Jurisdiccion { get; set; }
        public string Municipio { get; set; }
        public string NombreUnidadMedica { get; set; }
        public string Institucion { get; set; }
        public string CLUES { get; set; }
        public string NombreQuienElaboro { get; set; }
        public string CargoQuienElaboro { get; set; }
        public string NombreQuienAutorizo { get; set; }
        public string CargoQuienAutorizo { get; set; }
        public string ContactoTelefono { get; set; }
        public string ContactoCorreoElectronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosGenerales> DatosGenerales { get; set; }
    }
}
