//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evolucion
    {
        public int IdEvolucion { get; set; }
        public int IdPersona { get; set; }
        public Nullable<short> Evolucion1 { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public Nullable<System.DateTime> FechaDefunción { get; set; }
        public string FolioCertificadoDefunción { get; set; }
        public Nullable<bool> Defuncion2019nCoV { get; set; }
    
        public virtual DatosGenerales DatosGenerales { get; set; }
    }
}
