//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionFormato
    {
        public int IdInfFormato { get; set; }
        public int IdPersona { get; set; }
        public string NombreQuienElaboro { get; set; }
        public string CargoQuienElaboro { get; set; }
        public string NombreQuienAutorizo { get; set; }
        public string CargoQuienAutorizo { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public string ContactoTelefono { get; set; }
        public string ContactoCorreoElectronico { get; set; }
    
        public virtual DatosGenerales DatosGenerales { get; set; }
    }
}
