//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorio
    {
        public int IdLaboratorio { get; set; }
        public int IdPersona { get; set; }
        public bool SeTomoMuestraPaciente { get; set; }
        public string LaboratorioDiagnostico { get; set; }
        public Nullable<bool> ExudadoFaringeo { get; set; }
        public Nullable<bool> ExudadoNasofaringeo { get; set; }
        public Nullable<bool> LavadoBronquial { get; set; }
        public Nullable<bool> BiopsiaPulmon { get; set; }
        public Nullable<System.DateTime> FechaTomaMuestra { get; set; }
        public Nullable<System.DateTime> FechaEnvioMuestra { get; set; }
        public Nullable<System.DateTime> FechaRecepcionMuestra { get; set; }
        public Nullable<System.DateTime> FechaResultado { get; set; }
        public string Resultado { get; set; }
    
        public virtual DatosGenerales DatosGenerales { get; set; }
    }
}
