//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneProject.Medical.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int IdTratamiento { get; set; }
        public int IdPersona { get; set; }
        public string RecibioTrataAntipireticoAnalgesico { get; set; }
        public Nullable<System.DateTime> FechaInicioTrataAntipireticoAnalgesico { get; set; }
        public bool Paracetamol { get; set; }
        public bool Ibuprofeno { get; set; }
        public bool AcidoAcetilsalicilico { get; set; }
        public bool ClonixinatoLisina { get; set; }
        public bool Naproxeno { get; set; }
        public bool Proxicam { get; set; }
        public bool MetamizolSodico { get; set; }
        public bool Diclofenaco { get; set; }
        public bool Ketorolaco { get; set; }
        public Nullable<bool> OtroAntipireticoAnalgesico { get; set; }
        public string RecibioTrataAntiviral { get; set; }
        public Nullable<System.DateTime> FechaInicioTrataAntiviral { get; set; }
        public bool Amantadina { get; set; }
        public bool Rimantadina { get; set; }
        public bool Oseltamivir { get; set; }
        public bool Zanamivir { get; set; }
        public bool Peramivir { get; set; }
        public bool Ribavirina { get; set; }
        public string OtroAntiviral { get; set; }
        public string RecibioTrataAntibiotico { get; set; }
        public Nullable<System.DateTime> FechaInicioTrataAntibiotico { get; set; }
        public bool Penicilina { get; set; }
        public bool Dicloxacilina { get; set; }
        public bool Ampicilina { get; set; }
        public bool Amikacina { get; set; }
        public bool Doxiciclina { get; set; }
        public bool Cefalosporina { get; set; }
        public bool Clindamicina { get; set; }
        public bool Claritromicina { get; set; }
        public bool Ciprofloxacino { get; set; }
        public bool Meropenem { get; set; }
        public bool Vancomicina { get; set; }
        public bool AmoxicilinaAcClauvulanico { get; set; }
        public Nullable<bool> OtrosAntibioticos { get; set; }
    
        public virtual DatosGenerales DatosGenerales { get; set; }
    }
}
